[Variables]


;;--;;
Calculator=["calc.exe"]
CCleaner=["C:\Path\To\App.exe"]

ControlPanel=[%SystemRoot%\system32\control.exe]

Discord=["C:\Users\aiden\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord"]
DocumentsFolder=["C:\Users\aiden\Documents"]
Downloads=["C:\Users\aiden\Downloads"]
FileExplorer=["C:\Users\aiden\Desktop"]
Github=["https://github.com/gmoddev"]

Gmail=["https://mail.google.com"]


MSIAfterburner=["C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe"]
NotepadPlusPlus=["C:\Program Files (x86)\Notepad++\notpad++.exe"]
obs=["C:\Program Files (x86)\OBS\OBS.exe"]
Onedrive=["C:\Path\To\App.exe"]
OneFingerDeathPunch=["C:\Path\To\App.exe"]
Opera=["C:\Path\To\App.exe"]
Origin=["C:\Path\To\App.exe"]
Overwatch=["C:\Path\To\App.exe"]
Pictures=["C:\Users\USERNAME\Pictures"]
RecycleBin=!execute [!RainmeterPluginBang "MeasureBinSize OpenBin"]
;RecycleBin=["C:\Dropbox\Data\Shortcuts\Uninstall_Programs"] ;Uncomment this for "Uninstall programs"
Search=["#CURRENTPATH#Search.exe"]
Skype=["C:\Program Files (x86)\Skype\Phone\Skype.exe"]
Skyrim=["steam://rungameid/72850"]
SonyVegas=["C:\Path\To\App.exe"]
Soundcloud="https://soundcloud.com"
Speedrunners=["steam://rungameid/207140"]
Spotify=["C:\Users\aiden\AppData\Roaming\Spotify"]
Steam=["C:\Program Files (x86)\Steam\Steam.exe"]
SublimeText=["C:\Path\To\App.exe"]
TeamFortress=["steam://rungameid/440"]
Teamspeak=["C:\Path\To\App.exe"]
TeamViewer=["C:\Program Files (x86)\TeamViewer\TeamViewer.exe"]
Terminal=["cmd"]
AAuTorrent=["C:\Users\Karl\AppData\Roaming\uTorrent\uTorrent.exe"]
uTorrent=["%APPDATA%\uTorrent\uTorrent.exe"]
VideosFolder=["C:\Users\USERNAME\Videos"]
VLCMediaPlayer=["C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"]
WindowsMediaPlayer=["%ProgramFiles(x86)%\Windows Media Player\wmplayer.exe"]
Witcher=["steam://rungameid/292030"]
WoW=["C:\Path\To\App.exe"]
XBMC=["C:\Path\To\App.exe"]
XSplit=["C:\Program Files (x86)\SplitmediaLabs\XSplit Broadcaster\XSplit.Core.exe"]
Youtube="https://www.youtube.com/"
